# Generated by Django 4.2.1 on 2023-05-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'serious'), (2, 'important'), (3, 'temporary')], default=1, verbose_name='Level'),
        ),
    ]
