# Generated by Django 4.2.1 on 2023-05-16 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_task_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.SmallIntegerField(choices=[(3, 'temporary'), (2, 'important'), (1, 'serious')], default=1, verbose_name='Level'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=64, verbose_name='Order ID')),
                ('title', models.CharField(max_length=64, verbose_name='Name')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('status', models.SmallIntegerField(choices=[(1, 'paid'), (2, 'unpaid')], default=1, verbose_name='Status')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='Administrator')),
            ],
        ),
    ]
