# Generated by Django 4.2.1 on 2023-05-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_profile_alter_order_status_alter_task_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='City')),
                ('count', models.IntegerField(verbose_name='Population')),
                ('img', models.FileField(max_length=128, upload_to='city/', verbose_name='LOGO')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'paid'), (2, 'unpaid')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.SmallIntegerField(choices=[(2, 'important'), (1, 'serious'), (3, 'temporary')], default=1, verbose_name='Level'),
        ),
    ]
